
const GAME_CONST = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    PLAYER_BASE_SPEED: 5,
    BOOST_MULTIPLAYER:2,
    BOOST_DURATION:120,
    INIT_BOOSTS:3,
    INIT_HEARTS: 4,
    SPAWN_INTERVAL: 60
}